spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootdb
    username: jxjxjxm
    password: JJJM214332
    generate-dll: true

referrals:
  github:
    url: https://raw.githubusercontent.com/Nearsoft/jobs/master/readme.md
mail:
  host: smtp.gmail.com
  port: 587
  username:
  password:
  properties:
    mail:
      smtp:
        starttls:
          enable: true
          required: true
        auth: true
        connectiontimeout: 5000
        timeout: 5000
        writetimeout: 5000